export const REQUEST_REGISTRATION = "REQUEST_REGISTRATION";
export const SUCCESS_REGISTRATION = "SUCCESS_REGISTRATION";
export const FAIL_REGISTRATION = "FAIL_REGISTRATION";

export const REQUEST_PROFILE = "REQUEST_PROFILE";
export const SUCCESS_PROFILE = "SUCCESS_PROFILE";
export const FAIL_PROFILE = "FAIL_PROFILE";