export const REQUEST_PATIENT = "REQUEST_PATIENT";
export const SUCCESS_PATIENT = "SUCCESS_PATIENT";
export const FAIL_PATIENT= "FAIL_PATIENT";

export const REQUEST_PATIENT_GROUP = "REQUEST_PATIENT_GROUP";
export const SUCCESS_PATIENT_GROUP = "SUCCESS_PATIENT_GROUP";
export const FAIL_PATIENT_GROUP= "FAIL_PATIENT_GROUP";

export const REQUEST_PATIENT_SINGLE = "REQUEST_PATIENT_SINGLE";
export const SUCCESS_PATIENT_SINGLE = "SUCCESS_PATIENT_SINGLE";
export const FAIL_PATIENT_SINGLE = "FAIL_PATIENT_SINGLE";

export const REQUEST_PATIENT_APPOINTMENT = "REQUEST_PATIENT_APPOINTMENT";
export const SUCCESS_PATIENT_APPOINTMENT  = "SUCCESS_PATIENT_APPOINTMENT";
export const FAIL_PATIENT_APPOINTMENT  = "FAIL_PATIENT_APPOINTMENT";

export const REQUEST_PATIENT_SEARCH = "REQUEST_PATIENT_SEARCH";
export const SUCCESS_PATIENT_SEARCH  = "SUCCESS_PATIENT_SEARCH";
export const FAIL_PATIENT_SEARCH  = "FAIL_PATIENT_SEARCH";

export const REQUEST_APPOINTMENT_SEARCH = "REQUEST_APPOINTMENT_SEARCH";
export const SUCCESS_APPOINTMENT_SEARCH  = "SUCCESS_APPOINTMENT_SEARCH";
export const FAIL_APPOINTMENT_SEARCH  = "FAIL_APPOINTMENT_SEARCH";
